### ISSUE TITLE
Freezes when "go" inmediatly after receive "bestmove"

### ISSUE THREAD

**Issue by supertorpe** [niklasf/stockfish.wasm#13]
If we configure a loop of:
a) position fen ...
b) go depth ...
c) wait for "bestmove"

The engine freezes in the second iteration. Workaround is to delay the "go" command few milliseconds after receive the previous "bestmove".

logs:
stockfish.onMessage:Stockfish 120719 64 POPCNT by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
onMessage:id name Stockfish 120719 64 POPCNT
onMessage:id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott
onMessage:
onMessage:option name Debug Log File type string default 
onMessage:option name Contempt type spin default 24 min -100 max 100
onMessage:option name Analysis Contempt type combo default Both var Off var White var Black var Both
onMessage:option name Threads type spin default 1 min 1 max 4
onMessage:option name Hash type spin default 16 min 1 max 16
onMessage:option name Clear Hash type button
onMessage:option name Ponder type check default false
onMessage:option name MultiPV type spin default 1 min 1 max 500
onMessage:option name Skill Level type spin default 20 min 0 max 20
onMessage:option name Move Overhead type spin default 30 min 0 max 5000
onMessage:option name Minimum Thinking Time type spin default 20 min 0 max 5000
onMessage:option name Slow Mover type spin default 84 min 10 max 1000
onMessage:option name nodestime type spin default 0 min 0 max 10000
onMessage:option name UCI_Chess960 type check default false
onMessage:option name UCI_AnalyseMode type check default false
onMessage:uciok
**postMessage:position fen 2k5/8/8/8/8/5P2/8/4K3 w - - 0 1
postMessage:go depth 40**
onMessage:info depth 1 seldepth 1 multipv 1 score cp 4795 nodes 6 nps 6000 time 1 pv e1f2
onMessage:info depth 2 seldepth 2 multipv 1 score cp 4795 nodes 17 nps 269 time 63 pv e1f2 c8b7
onMessage:info depth 3 seldepth 3 multipv 1 score cp 4795 nodes 62 nps 607 time 102 pv e1f2 c8c7 f2g2
onMessage:info depth 4 seldepth 4 multipv 1 score cp 4795 nodes 121 nps 1152 time 105 pv e1f2 c8c7 f2g2 c7b6
onMessage:info depth 5 seldepth 5 multipv 1 score cp 4795 nodes 254 nps 2116 time 120 pv e1f2 c8c7 f2g2 c7c6 g2g3
onMessage:info depth 6 seldepth 6 multipv 1 score cp 4795 nodes 420 nps 3255 time 129 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6
onMessage:info depth 7 seldepth 7 multipv 1 score cp 4795 nodes 716 nps 5114 time 140 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6 g3f4
onMessage:info depth 8 seldepth 8 multipv 1 score cp 4795 nodes 1080 nps 7448 time 145 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6 g3f4 d6e6
onMessage:info depth 9 seldepth 9 multipv 1 score cp 4795 nodes 1709 nps 10614 time 161 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6 g3f4 d6e6 f4g4
onMessage:info depth 10 seldepth 10 multipv 1 score cp 4795 nodes 2145 nps 12257 time 175 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6 g3f4 d6e6 f4g4 e6e5
onMessage:info depth 11 seldepth 11 multipv 1 score cp 4795 nodes 2987 nps 16594 time 180 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6 g3f4 d6e6 f4g4 e6e5 g4g5
onMessage:info depth 12 seldepth 12 multipv 1 score cp 4795 nodes 3892 nps 21037 time 185 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6 g3f4 d6e6 f4g4 e6f7 g4g5 f7f8
onMessage:info depth 13 seldepth 13 multipv 1 score cp 4795 nodes 4974 nps 24746 time 201 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6 g3f4 d6e6 f4g4 e6f7 g4g5 f7f8 g5f5
onMessage:info depth 14 seldepth 14 multipv 1 score cp 4795 nodes 6361 nps 29863 time 213 pv e1f2 c8c7 f2g2 c7c6 g2g3 c6d6 g3f4 d6e6 f4g4 e6f7 g4g5 f7g8 g5f5 g8g7
onMessage:info depth 15 seldepth 15 multipv 1 score cp 4796 nodes 10885 nps 49477 time 220 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7g8 f3f4 g8g7 f4f5
onMessage:info depth 16 seldepth 16 multipv 1 score cp 4796 nodes 12521 nps 54916 time 228 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7g8 f3f4 g8f8 f4f5 f8e8
onMessage:info depth 17 seldepth 17 multipv 1 score cp 4796 nodes 14304 nps 60610 time 236 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7g8 f3f4 g8g7 f4f5 g7f8 e6f6
onMessage:info depth 18 seldepth 18 multipv 1 score cp 4796 nodes 16047 nps 64967 time 247 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7g8 f3f4 g8g7 f4f5 g7f8 e6f6 f8g8
onMessage:info depth 19 seldepth 19 multipv 1 score cp 4796 nodes 18119 nps 69688 time 260 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7g8 f3f4 g8g7 f4f5 g7f8 e6f6 f8g8 f6g6
onMessage:info depth 20 seldepth 20 multipv 1 score cp 4796 nodes 21198 nps 79097 time 268 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7g8 f3f4 g8g7 f4f5 g7f8 e6f6 f8g8 f6g6 g8f8
onMessage:info depth 21 seldepth 21 multipv 1 score cp 4797 nodes 28969 nps 103831 time 279 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7g8 f3f4 g8g7 f4f5 g7f8 e6f6 f8g8 f6e7 g8h7 e7e6
onMessage:info depth 22 seldepth 22 multipv 1 score cp 4797 nodes 32972 nps 116098 time 284 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7g8 f3f4 g8g7 f4f5 g7f8 e6f6 f8g8 f6e7 g8h7 e7e6 h7h6
onMessage:info depth 23 seldepth 24 multipv 1 score cp 5916 nodes 50508 nps 165058 time 306 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7d6 f3f4 d6d5 f4f5 d5e4 f5f6 e4f3 f6f7 f3g2 f7f8q
onMessage:info depth 24 seldepth 24 multipv 1 score cp 5924 nodes 62971 nps 198022 time 318 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7d6 f3f4 d6d5 f4f5 d5c4 g6g5 c4b3 f5f6 b3b2 f6f7 b2a3 f7f8q a3a4
onMessage:info depth 25 seldepth 26 multipv 1 score cp 5924 nodes 69512 nps 213226 time 326 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7d6 f3f4 d6d5 f4f5 d5c4 g6g5 c4b3 f5f6 b3a2 g5g6 a2a3 g6g7 a3a2 f6f7
onMessage:info depth 26 seldepth 27 multipv 1 score cp 5929 nodes 84147 nps 229909 time 366 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 f4f5 f8g8 g6f6 g8f8 f6e6 f8g7 f5f6 g7g6 e6e7 g6f5 f6f7 f5e4 f7f8q
onMessage:info depth 27 seldepth 28 multipv 1 score cp 5933 nodes 95599 nps 252907 time 378 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 f4f5 f8g8 g6f6 g8f8 f6e6 f8g7 f5f6 g7g6 e6e7 g6f5 f6f7 f5e4 f7f8q e4d3
onMessage:info depth 28 seldepth 29 multipv 1 score cp 5933 nodes 102350 nps 254601 time 402 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 f4f5 f8g8 g6f6 g8f8 f6e6 f8g7 f5f6 g7g6 e6e7 g6f5 f6f7 f5e4 f7f8q e4d3 e7f6
onMessage:info depth 29 seldepth 31 multipv 1 score cp 5943 nodes 128965 nps 300617 time 429 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f6e5 g8f7 e5f5 f7g7 f5e6 g7h6 f4f5 h6g5 f5f6 g5f4 e6e7 f4e5
onMessage:info depth 30 seldepth 30 multipv 1 score cp 5943 nodes 140525 nps 322305 time 436 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f6e5 g8f7 e5f5 f7g7 f5e6 g7h6 f4f5 h6g5 f5f6 g5f4 e6e7 f4e5 f6f7 e5d5
onMessage:info depth 31 seldepth 31 multipv 1 score cp 5943 nodes 152153 nps 340387 time 447 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f6e5 g8f7 e5f5 f7g7 f5e6 g7h6 f4f5 h6g5 f5f6 g5f4 e6e7 f4e5 f6f7 e5d5 f7f8q
onMessage:info depth 32 seldepth 32 multipv 1 score cp 5943 nodes 162886 nps 354871 time 459 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f6e5 g8f7 e5f5 f7g7 f5e6 g7h6 f4f5 h6g5 f5f6 g5f4 e6e7 f4e5 f6f7 e5d5 f7f8q d5d4
onMessage:info depth 33 seldepth 33 multipv 1 score cp 5943 nodes 180829 nps 382302 time 473 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f6e5 g8f7 e5f5 f7g7 f5e6 g7h6 f4f5 h6g5 f5f6 g5f4 e6e7 f4e5 f6f7 e5d5 f7f8q d5d4 e7f6
onMessage:info depth 34 seldepth 34 multipv 1 score cp 5943 nodes 214202 nps 432731 time 495 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f6e5 g8f7 e5f5 f7g7 f5e6 g7h6 f4f5 h6g5 f5f6 g5f4 e6e7 f4e5 f6f7 e5d5 f7f8q d5d4 e7f6 d4e4
onMessage:info depth 35 seldepth 39 multipv 1 score cp 5952 nodes 412522 nps 712473 time 579 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f6e7 g8g7 f4f5 g7h6 f5f6 h6g5 e7e6 g5f4 f6f7 f4e3 f7f8q e3d3 e6d5 d3e2 f8a3 e2d1 d5d4 d1e1
onMessage:info depth 36 seldepth 39 multipv 1 score cp 5961 nodes 538908 nps 825280 time 653 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f4f5 g8h7 f6e6 h7h6 f5f6 h6g5 f6f7 g5f4 f7f8q f4e3 e6d5 e3d3 f8a3 d3e2 d5d4 e2f2 a3h3 f2g1 h3f3 g1h2 d4e3
onMessage:info depth 37 seldepth 40 multipv 1 score cp 5971 nodes 640611 nps 904817 time 708 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8f8 g6f6 f8g8 f4f5 g8h7 f6e6 h7h6 f5f6 h6g5 f6f7 g5f4 f7f8q f4e3 e6d5 e3d3 f8a3 d3e2 d5d4 e2f2 a3h3 f2g1 h3f3 g1h2 d4e3 h2g1
onMessage:info depth 38 seldepth 41 multipv 1 score cp 5982 nodes 866075 nps 1079894 time 802 pv e1f2 c8c7 f2g3 c7d6 g3f4 d6e6 f4g5 e6f7 g5f5 f7e7 f5g6 e7e8 f3f4 e8e7 f4f5 e7f8 g6f6 f8e8 f6g7 e8d7 f5f6 d7c6 f6f7 c6b5 f7f8q b5a4 g7f6 a4b3 f6e5 b3c2 f8a3 c2d2 e5d4 d2e1 a3b3 e1f2 b3h3 f2g1
onMessage:info depth 39 seldepth 39 multipv 1 score mate 54 nodes 1598547 nps 1503807 hashfull 60 time 1063 pv e1f2 c8d7 f2g3 d7e7 g3g4 e7f6 g4f4 f6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7f8 e6f6 f8e8 f6f5 e8d8 f5f4 d8c7 f4g4 c7b7 g4g3 b7a8 f3f4 a8b8 g3g4 b8a7 f4f5 a7a8 g4h5 a8b7 h5g5 b7a7
onMessage:info depth 40 seldepth 55 multipv 1 score mate 40 nodes 2199565 nps 1705089 hashfull 66 time 1290 pv e1f2 c8d7 f2g3 d7e7 g3g4 e7f6 g4f4 f6e6 f4g5 e6f7 g5f5 f7g7 f5e6 g7f8 e6f6 f8e8 f6g6 e8e7 f3f4 e7e8 f4f5 e8f8 g6f6 f8e8 f6g7 e8d7 f5f6 d7c6 f6f7 c6c5 f7f8q c5c4 g7f6 c4d3 f8a3 d3e2 f6e6 e2f2 a3f8 f2e2 e6d5 e2e3
onMessage:bestmove e1f2 ponder c8d7
**postMessage:position fen 2k5/8/8/8/8/5P2/5K2/8 b - - 1 1
postMessage:go depth 40**

**Comment by niklasf** [comment]
Thanks for reporting. This was happening, because the thread that printed `bestmove` had not yet released the mutex that guards printing, so even doing just `isready` in the callback would deadlock.
