### ISSUE TITLE
Expose as web worker

### ISSUE THREAD

**Issue by patrickfrank1** [niklasf/stockfish.wasm#17]
Is it possible to expose stockfish.wasm as web worker, similar as to what you did in https://github.com/niklasf/stockfish.js? So that one could run

```var stockfish = new Worker(wasmThreadSupported ? 'stockfish.worker.js' : 'stockfish.js');```

Unfortunately when I tried this out it didn't work...

**Comment by niklasf** [comment]
The search threads already run in workers. The file `stockfish.js` is just glue and should not block.
