### ISSUE TITLE
Reuse(?) Stockfish

### ISSUE THREAD

**Issue by ArneVogel** [niklasf/stockfish.wasm#23]
I noticed that the stockfish assets are re-requested every time Stockfish() is called. You can see it happening on [this site](https://listudy.org/en/studies/play#rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201) after playing each move.
Code running after each move: https://github.com/ArneVogel/listudy/blob/master/assets/js/play_stockfish.js#L31

Is there a way to reuse(?) a stockfish instance for each move instead of creating one each time?

**Comment by niklasf** [comment]
`Stockfish()` creates a new instance each time it's called. Instead keep a reference to the result.

To avoid loading assets again when the user revisits the page, normal HTTP caching will do.

**Comment by ArneVogel** [comment]
Ok I got it, thanks.
For anybody else reading this in the future, save the sf instance here:
```
<script>
Stockfish().then(sf => {
  my_stockfish = sf; // you can now use my_stockfish outside of the .then to postMessage new commands
});
</script>
```
