### ISSUE TITLE
position move and position fen messages generate different stockfish output

### ISSUE THREAD

**Issue by honkskillet** [niklasf/stockfish.wasm#28]
This might be expected behavior.  

From let's say you make a move from a given starting fen, would you expect
`position move  the-move`
to generate the same output as
`position fen the-fen-after-the-move`

In my tests it looks like 'position fen ...' is naive to what came before in the game.  Is this expected?

See my question on stachexchange which has some engine output
https://chess.stackexchange.com/questions/33903/stockfish-depth-calculations/33906#33906

**Comment by niklasf** [comment]
Answered on Stackexchange.
