### ISSUE TITLE
wasmThreadSupported returns false in node

### ISSUE THREAD

**Issue by honkskillet** [niklasf/stockfish.wasm#29]
Hello,
The function wasmThreadSupported in the readme returns false in node.  Am I correct to assume that this function should only be used in the browser setting? I already have your package running well on node 14 with the experimental flags enabled.  

In general I am looking for a robust way to check to see if stockfish.wasm is support in whatever environment I am running it in.  In my project right now I use stockfish.wasm on the node backend and stockfish.js on the front end.  But in both environment I'd like to check to see if stockfish.wasm is supported and if not fall back to  stockfish.js.  I'm writing a wrapper that does so (and also promisifies some of the UCI messages).

Perhaps it would be better if wasmThreadSupported was a method on this projects object? ...
`
const Stockfish = require('stockfish.wasm');
Stockfish. wasmThreadSupported();
`
That would help this function/method stay current with future updates to stockfish.wasm.

Or am I reinventing the wheel?  Have robust ways of checking stockfish.wasm and falling back to stockfish.js already been worked out?

**Comment by niklasf** [comment]
Correct, the current feature detection is only intended for browser, but if you can figure out a way to feature test for node, I am happy to add it.

Some of these things can be pretty application specific (growable memory required? fallback to single-threaded wasm? fallback to js? run a pool of fallbacks? ...), so I've hesitated to add more than the example.

**Comment by honkskillet** [comment]
Related question, in the readme it says that the only browser that supports this package is firefox.  But when I go to https://lichess.org/analysis, even in safari it says it is using "Stockfish 10+ WASM".  Is that this package (or the .wasm from stockfish.js)?

**Comment by niklasf** [comment]
Multi-threaded WASM is supported by Firefox, Chromium (and thus Chrome and Edge).

Stockfish 10+ WASM is single threaded WASM, though. Multi-threaded WebAssembly on Lichess would show as WASMX (for eXperimental).

**Comment by honkskillet** [comment]
Ah.  Yes, my Firefox needed to be updated.  I get WASMX when I check on Chrome and Firefox now.

I'm boing to close this issue d/t your first response

**Comment by honkskillet** [comment]
PS.  What I've been doing on Node is pretty Naive.  i just check that the version is 14 and that the experimental flags are included in the process variable.
