### ISSUE TITLE
How do I set the HTTP headers

### ISSUE THREAD

**Issue by Marc-9** [niklasf/stockfish.wasm#31]
After successfully compiling the the WASM and JS using emscripten, I noticed an error accessing the Shared Buffer array as I had not set the proper HTTP Headers
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
In my files.

I know what the issue is however I am failing to find an easy explanation on how to set these values, must I redirect the user to a page and set the values then? Or can I not just have some code that sets those values when the page loads.
Ive been reading the docs at 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest]

Please point me in the direction where I can get the answer to this question, as I clearly must be missing an obvious fact that I fail to grasp regarding HTTP headers.
Thanks

**Comment by niklasf** [comment]
Hi. Usually this is done in web server configuration, so it depends on which server you're using.

**Comment by Marc-9** [comment]
Thank you for the reply, is there no way to test this in my localhost?
I am using MAMP to run my web server

**Comment by niklasf** [comment]
That sounds correct. Note that `require-corp` is also required for the stockfish files, not just index.html. You can use the network tab of your browser developer tools to verify that the headers are indeed set.

I believe Chrome does not require any of this when testing on localhost.

**Comment by Marc-9** [comment]
I have verified this in the network tab so far my main index page returns the headers
`HTTP/2 200 OK
date: Sun, 14 Mar 2021 19:15:24 GMT
content-type: text/html; charset=UTF-8
x-powered-by: PHP/7.3.27
**cross-origin-embedder-policy: require-corp**
**cross-origin-opener-policy: same-origin**
access-control-allow-origin: same-origin
cross-origin-embedder-policy: require-corp
cf-cache-status: DYNAMIC
cf-request-id: 08d3c3343b000027f451178000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=Q69rkxgvPXNsmt%2FJVPLlZUEaxL6jO074pAAxsZylv1LuhRTkU%2BaWakSZDMCPjG%2F56TV3Vpm%2BCAXp01dYV5aAlNWncP1TA%2BSkibX5qUp6Q8Vv2wTW1%2Fs%3D"}],"max_age":604800,"group":"cf-nel"}
nel: {"max_age":604800,"report_to":"cf-nel"}
server: cloudflare
cf-ray: 62ffd499fb6727f4-SLC
content-encoding: br
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
X-Firefox-Spdy: h2`

and the stockfish.js returns

`HTTP/2 200 OK
date: Sun, 14 Mar 2021 17:55:28 GMT
content-type: application/javascript
last-modified: Sun, 14 Mar 2021 06:41:00 GMT
access-control-allow-origin: same-origin
**cross-origin-embedder-policy: require-corp**
cache-control: max-age=14400
cf-cache-status: HIT
age: 145
cf-request-id: 08d37a0856000027c841b2d000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=8d67qbNcCRgbWNJqaaq6KUxI2coMhGdp0fJvdMf2eDXG6qUHd6Oyglv2wVJRgmKSDgFjiLz4wHifQnt%2BLpM9dqcygwXBlPHO5fYgLbARr4xi0ihT%2Fw4%3D"}],"max_age":604800,"group":"cf-nel"}
nel: {"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
server: cloudflare
cf-ray: 62ff5f86efbb27c8-SLC
content-encoding: br
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
X-Firefox-Spdy: h2`

The stockfish.wasm and .worker.js return similar headers to the ones shown above, both containing the required headers


Yet my console still outputs the error (in Firefox 86.0.1)
Uncaught ReferenceError: SharedArrayBuffer is not defined
    Stockfish https://thematchpredictor.com/stockfish/stockfish.js:32
    <anonymous> https://thematchpredictor.com/stockfish/:34

In Safari 13.1.3
[Error] ReferenceError: Can't find variable: SharedArrayBuffer
	(anonymous function) (stockfish.js:32:185)
	Global Code (stockfish:34)

In chrome (89.0.4389.90) it runs but says 
SharedArrayBuffer usage is restricted to cross-origin isolated sites
SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
falling back to ArrayBuffer instantiation

so clearly it does not work there either but is just allowing it



Now it could be possible that the .htaccess specifications are not giving the required headers to the .wasm stockfish files however I am not sure as that is not even an asset that

**Comment by Marc-9** [comment]
Reading https://developer.chrome.com/blog/enabling-shared-array-buffer/
And looking at the response headers for other sites that use this repo it seems they all have other response headers set, specifically
access-control-allow-origin: *

**Comment by niklasf** [comment]
I see the headers twice in your index.html. CORS headers like `access-control-allow-origin` are unrelated.

**Comment by Marc-9** [comment]
Never in a million years would I have thought sending the same header twice would cause a problem, this has resolved the issue besides the
wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type '' expected 'application/wasm' stockfish.js:76:425
falling back to ArrayBuffer instantiation

however those do not stop the execution
I will also need to find a work around for safari, how do the other sites workaround? Do they just fall back to the single threaded implementation?

Thank you so much for your patience and assistance

**Comment by niklasf** [comment]
Yay :)

> wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type '' expected 'application/wasm' stockfish.js:76:425

The way to avoid this would be serving the `stockfish.wasm` file with header `Content-Type: application/wasm`.

> I will also need to find a work around for safari, how do the other sites workaround? Do they just fall back to the single threaded implementation?

Yes, at least that's what lichess.org does.

**Comment by zalo** [comment]
For any future intrepid travelers, I found this solution to work nicely when serving from Github Pages:
https://github.com/gzuidhof/coi-serviceworker
